<?php
return array(
    '/center/config/getconfig'=>[
        "access_by_php_class"=>[],
        "allow_ip"=>["local","172.31.123.248"],
        "content_by_php_class"=>array('class'=>'scripts\\AdminCtrl','method'=>'invoke',"params"=>["fname"=>"getconfig"]),
        "comment"=>"获取参数配置",
    ],
    '/center/admin/setaccountstatus'=>[
        "access_by_php_class"=>[],
        "allow_ip"=>["local","172.31.123.248"],
        "content_by_php_class"=>array('class'=>'scripts\\AdminCtrl','method'=>'invoke',"params"=>["fname"=>"setaccountstatus"]),
        "comment"=>"设置封号",
    ],
    '/center/config/setconfig'=>[
        "access_by_php_class"=>[],
        "allow_ip"=>["local","172.31.123.248"],
        "content_by_php_class"=>array('class'=>'scripts\\AdminCtrl','method'=>'invoke',"params"=>["fname"=>"setconfig"]),
        "comment"=>"设置参数配置",
    ],
    '/center/admin/changeres'=>[
        "access_by_php_class"=>[],
        "allow_ip"=>["local","172.31.123.248"],
        "content_by_php_class"=>array('class'=>'scripts\\AdminCtrl','method'=>'invoke',"params"=>["fname"=>"changeres"]),
        "comment"=>"加减资源",
    ],
    '/center/admin/changeuserlvl'=>[
        "access_by_php_class"=>[],
        "allow_ip"=>["local","172.31.123.248"],
        "content_by_php_class"=>array('class'=>'scripts\\AdminCtrl','method'=>'invoke',"params"=>["fname"=>"changeuserlvl"]),
        "comment"=>"用户等级修改",
    ],
    '/center/admin/userinfo'=>[
        "access_by_php_class"=>[],
        "allow_ip"=>["local","172.31.123.248"],
        "content_by_php_class"=>array('class'=>'scripts\\AdminCtrl','method'=>'invoke',"params"=>["fname"=>"userinfo"]),
        "comment"=>"会员信息",
    ],
);
