<?php
return array(
    '/center/hall/getnotice'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\HallCtrl','method'=>'invoke',"params"=>["fname"=>"getnotice"]),
        "comment"=>"获得公告",
    ],
    '/center/hall/getinvitecode'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\HallCtrl','method'=>'invoke',"params"=>["fname"=>"getinvitecode"]),
        "comment"=>"获得邀请码",
    ],
    '/center/hall/getmyteam'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\HallCtrl','method'=>'invoke',"params"=>["fname"=>"getmyteam"]),
        "comment"=>"获得团队直推",
    ],
    '/center/hall/loadhall'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\HallCtrl','method'=>'invoke',"params"=>["fname"=>"loadhall"]),
        "comment"=>"加载大厅",
    ],
    '/center/hall/setfeedback'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\HallCtrl','method'=>'invoke',"params"=>["fname"=>"setfeedback"]),
        "comment"=>"设置意见反馈",
    ],
    '/center/hall/authentication'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\HallCtrl','method'=>'invoke',"params"=>["fname"=>"authentication"]),
        "comment"=>"实名认证",
    ],
    '/center/hall/bindgoogle'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\HallCtrl','method'=>'invoke',"params"=>["fname"=>"bindgoogle"]),
        "comment"=>"绑定Google验证",
    ],
    '/center/hall/getmyassets'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\HallCtrl','method'=>'invoke',"params"=>["fname"=>"getmyassets"]),
        "comment"=>"获得我的资产",
    ],
);
