<?php
return array(
    '/center/login/register'=>[
        "access_by_php_class"=>[],
        "content_by_php_class"=>array('class'=>'scripts\\LoginCtrl','method'=>'invoke',"params"=>["fname"=>"register"]),
        "comment"=>"注册接口",
    ],
    '/center/login/login'=>[
        "access_by_php_class"=>[],
        "content_by_php_class"=>array('class'=>'scripts\\LoginCtrl','method'=>'invoke',"params"=>["fname"=>"login"]),
        "comment"=>"登录接口",
    ],
    '/center/login/loaduser'=>[
        "access_by_php_class"=>[['class'=>'scripts\\Access','method'=>'access',"params"=>[]],],
        "content_by_php_class"=>array('class'=>'scripts\\LoginCtrl','method'=>'invoke',"params"=>["fname"=>"loaduser"]),
        "comment"=>"获取玩家信息",
    ],
    '/center/login/findpassword'=>[
        "access_by_php_class"=>[],
        "content_by_php_class"=>array('class'=>'scripts\\LoginCtrl','method'=>'invoke',"params"=>["fname"=>"findpassword"]),
        "comment"=>"找回密码",
    ],
    '/center/login/sms_cr'=>[
        "access_by_php_class"=>[],
        "content_by_php_class"=>array('class'=>'scripts\\LoginCtrl','method'=>'invoke',"params"=>["fname"=>"sms_cr"]),
        "comment"=>"发送短信",
    ],
    '/center/login/sms_cr_inter'=>[
        "access_by_php_class"=>[],
        "content_by_php_class"=>array('class'=>'scripts\\LoginCtrl','method'=>'invoke',"params"=>["fname"=>"sms_cr_inter"]),
        "comment"=>"发送短信国际",
    ],
    '/center/login/getqrcode'=>[
        "access_by_php_class"=>[],
        "content_by_php_class"=>array('class'=>'scripts\\LoginCtrl','method'=>'invoke',"params"=>["fname"=>"getqrcode"]),
        "comment"=>"获得图形验证",
    ],
);
